// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OyunProjee.Model.Context;

namespace OyunProjee.Model.Migrations
{
    [DbContext(typeof(OyunContext))]
    [Migration("20230705181820_created_db")]
    partial class created_db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OyunProjee.Model.Entities.Karakter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FızıkselOzellik")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("Gucu")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("OyunAdı")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OyunId")
                        .HasColumnType("int");

                    b.Property<string>("OyuncuAdı")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OyuncuOzellikleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vurus")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OyunId");

                    b.ToTable("Karakters");
                });

            modelBuilder.Entity("OyunProjee.Model.Entities.Oyun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Fiyat")
                        .HasMaxLength(50)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("KurulusTarihi")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.Property<string>("OyunAdı")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Türü")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Oyuns");
                });

            modelBuilder.Entity("OyunProjee.Model.Entities.Karakter", b =>
                {
                    b.HasOne("OyunProjee.Model.Entities.Oyun", "Oyun")
                        .WithMany()
                        .HasForeignKey("OyunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oyun");
                });
#pragma warning restore 612, 618
        }
    }
}
